version: '3.8'

services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
      args:
        path: ${PROJECT_NAME}
    image: ${PROJECT_NAME}-image:latest
    container_name: ${PROJECT_NAME}-container
    ports:
      - "${PORT:-3000}:3000"
    env_file:
      - ${ENV_FILE:-${PROJECT_NAME}/.env}
    environment:
      - NODE_ENV=production
    restart: unless-stopped
